version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "db:5432", "--", "gunicorn", "hospital_inventory_management.wsgi:application", "--bind", "0.0.0.0:8000", "--access-logfile", "-", "--error-logfile", "-"]
    volumes:
      - .:/app
      - ./tmp:/tmp
      - ./csv_logs:/home/root491/csv_logs
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "db:5432", "--", "celery", "-A", "hospital_inventory_management", "worker", "--loglevel=info"]
    volumes:
      - .:/app
      - ./csv_logs:/home/root491/csv_logs
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "db:5432", "--", "celery", "-A", "hospital_inventory_management", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
