version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...' &&
        while ! nc -z $DATABASE_HOST $DATABASE_PORT; do sleep 1; done &&
        echo 'PostgreSQL is up!' &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn hospital_inventory_management.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - ./csv_logs:/home/root491/csv_logs
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  redis:
    image: redis:6

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...' &&
        while ! nc -z $DATABASE_HOST $DATABASE_PORT; do sleep 1; done &&
        celery -A hospital_inventory_management worker --loglevel=info
      "
    volumes:
      - .:/app
      - ./csv_logs:/home/root491/csv_logs
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...' &&
        while ! nc -z $DATABASE_HOST $DATABASE_PORT; do sleep 1; done &&
        celery -A hospital_inventory_management beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
