# Generated by Django 5.1.7 on 2025-04-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_admin", "0002_organization_inventorymanager"),
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="inventory_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="main_admin.inventorymanager",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_products",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_products",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
