# Generated by Django 5.1.7 on 2025-04-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0003_order_confirmed_by_order_delivered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
