# Generated by Django 5.1.7 on 2025-04-07 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="status_choices",
            new_name="status",
        ),
    ]
