# Generated by Django 5.1.7 on 2025-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nurse", "0003_alter_request_approved_by_alter_request_nurse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesteditems",
            name="quantity_returned",
            field=models.IntegerField(default=0),
        ),
    ]
